parameters:
  - name: pipeline_type
    type: string
    values: 
      - develop
      - pr
stages:
  - stage: build
    displayName: "build stage"
    jobs:
      - template: ../jobs/docker_build.yml
        parameters:
          pipeline_type: ${{ parameters. pipeline_type }}